version: '3.8'

services:
  web:
    container_name: nextjs
    build:
      context: ./
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '0.8'