version: '3.8'

services:
  web:
    hostname: web
    container_name: nextjs
    build:
      context: ./
    env_file:
      - ./.env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '0.8'
