version: '3.8'

services:
  web:
    hostname: web
    container_name: nextjs
    build:
      context: ./
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '0.8'
  nginx:
    image: nginx:latest
    container_name: nginx-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-web
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d api-test.benchpromos.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"