version: '3.8'

services:
  web:
    container_name: nextjs
    build:
      context: ./
      target: deps
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: always
