import { Icons } from '@/components/icons'
import {
  Award,
  DollarSign,
  Gift,
  LayoutDashboard,
  ListCollapse,
  PackageSearch,
  Percent,
  ShoppingBag,
  Star,
  Store,
  Users,
} from 'lucide-react'

export const dashboardSidebarItems = [
  {
    title: 'Dashboard',
    url: '/dashboard/general',
    icon: LayoutDashboard,
    isActive: true,
    items: [],
  },
  {
    title: 'Promoções',
    url: '/dashboard/sales',
    icon: DollarSign,
    isActive: true,
    items: [],
  },
  {
    title: 'Produtos',
    url: '/dashboard/products',
    icon: PackageSearch,
    isActive: true,
    items: [],
  },
  {
    title: 'Ofertas',
    url: '/dashboard/deals',
    icon: ShoppingBag,
    isActive: true,
    items: [],
  },
  {
    title: 'Varejistas',
    url: '/dashboard/retailers',
    isActive: true,
    icon: Store,
    items: [],
  },
  {
    title: 'Coupons',
    url: '/dashboard/coupons',
    isActive: true,
    icon: Icons.Tag,
    items: [],
  },
  {
    title: 'Cashbacks',
    url: '/dashboard/cashbacks',
    isActive: true,
    icon: Icons.RotateCcw,
    items: [],
  },
  {
    title: 'Descontos',
    url: '/dashboard/discounts',
    isActive: true,
    icon: Percent,
    items: [],
  },
  {
    title: 'Categorias',
    url: '/dashboard/categories',
    isActive: true,
    icon: ListCollapse,
    items: [],
  },
  {
    title: 'Usuários',
    url: '/dashboard/users',
    isActive: true,
    icon: Users,
    items: [],
  },
  {
    title: 'Benchmarks',
    url: '/dashboard/benchmarks',
    isActive: true,
    icon: Icons.LineChart,
    items: [],
  },
  {
    title: 'Recomendações',
    url: '/dashboard/recommendation',
    isActive: true,
    icon: Star,
    items: [],
  },
  {
    title: 'Awards',
    url: '/dashboard/awards',
    isActive: true,
    icon: Award,
    items: [],
  },
  {
    title: 'Sorteios',
    url: '/dashboard/giveaways',
    isActive: true,
    icon: Gift,
    items: [],
  },
]
