# name: Deploy

# on:
#   push:
#     branches: main

# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: SSH Conect
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           cd ${{ secrets.WORKDIR }}
#           git pull
#           docker compose build
#           docker compose up -d
#           yes | docker system prune -a --volumes
